# Generated by Django 5.1.3 on 2024-12-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_yourmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': [('can_view', 'Can view articles'), ('can_create', 'Can create articles'), ('can_edit', 'Can edit articles'), ('can_delete', 'Can delete articles')],
            },
        ),
    ]
